### ISSUE TITLE
Quik начинает "подвисать" после соединения

### ISSUE THREAD

**Issue by qkgx** [buybackoff/QuikSharp#12]
Добрый день!

Столкнулся с тем, что после вызова конструктора QuikSharp.Quik() терминал Quik иногда начинает тормозить (подвисает). Программа QuikSharp стаканы при этом получает (работаю с тестовым примером). Версия терминала Quik 6.17.1.17, в корневой каталог Quik скопировал lua5.1.dll и lua51.dll (идущую в поставке с QuikSharp).

После закрытия программы QuikSharp терминал Quik "оживает".

Думал, что это связано с получением программой введенных вручную транзакций (про которые "не знает" программа - ловил исключение с этим связанное), однако проблема сохраняется даже при отсутствии таких транзакций.

**Comment by buybackoff** [comment]
Может быть много стаканов и компьютер слабый или мало ядер? В тестовом примере они выводятся в консоль, а консоль не самая быстрая штука.

**Comment by qkgx** [comment]
Подвисает даже на одном стакане. Машина достаточно мощная (12 ядер).

Пробовал отключать обработчики стаканов - проблема сохраняется (т.е. начинает "зависать" после вызова конструктора QuikSharp.Quik).

**Comment by qkgx** [comment]
Так же проблема воспроизводится если подключить QuikSharp к Windows Forms приложению.

**Comment by buybackoff** [comment]
Там есть issue с потоками в Windows Forms. Мы пока не разбирались и тупо силой засунули QuikSharp в отдельный поток. Хотя он иззначально задумывался как thread safe. Буду благодарен, если найдете корень проблемы.

**Comment by qkgx** [comment]
Т.е. проблема должна возникать в Windows Forms и отсутствовать в Console Application?

**Comment by buybackoff** [comment]
В консоли все отлично работает на нескольких машинах с разными версиями Квика. Вы используете последний коммит/нюгет? Если да, то я даже не знаю как удаленно помочь.

**Comment by qkgx** [comment]
Да, я использую последний коммит (master). 

Я могу поднять box с удаленным рабочим столом, тогда сможете посмотреть. Сделать?

**Comment by buybackoff** [comment]
Сорри, не смогу. Код абсолютно открытый как раз для таких случаев. И версия
только 0.2.
Попробуйте еще коммит
https://github.com/buybackoff/QuikSharp/commit/1c4f9b333f5e6f73ead74f30b4c33b8680e23cc3,
я решил одну очень коварную проблему в следующем коммите возможно излишне
радикально и разделил канал на два, хотя только замены JSON библиотеки в
Луа хватило бы.


2015-04-27 19:03 GMT+03:00 KGX <notifications@github.com>:

**Comment by qkgx** [comment]
Сейчас запустил на другом квике (6.16.1.15) и на другой машине (послабее конфигурация - 4 ядра вместо 12 и 16 Гб RAM вместо 32) - смог подписаться на 1000 стаканов (все фьючерсы и опционы) без зависания терминала (при такой подписке приходит около 30 стаканов в секунду).

**Comment by buybackoff** [comment]
Здорово! Хорошая новость :) Может от версии Квика зависит, то ли 15 то ли 14 была вообще битая для Луа. Это черный ящик, я даже на своей собственной машине долго гадал в чем дело, например с историей про забытый прокси lua51.dll без точки.

**Comment by qkgx** [comment]
Вот сейчас на втором боксе попробовал обновить Quik до 6.17.1.17 - все так же прекрасно работает как и на 6.16.1.15. Т.е. тут дело не в версии квика а в чем-то другом. Досадно что непонятно в чем именно.

По поводу производительности MarketData источника: в конце дня, на подкачивании всех сделок получал от QuikSharp около 1500 сообщений в секунду.

**Comment by buybackoff** [comment]
Это хорошо или недостаточно!? :) 1500 в сек это как раз те самые 60-70 микросекунд, быстрее которых сериализация не дает. Но так как, как мне кажется, это получение запаздывающего потока, а не обмен в реальном времени, то можно пережить?

**Comment by qkgx** [comment]
Это очень хорошо :) и для практического использования большинства алгоритмов вполне достаточно. Внутренние задержки Quik Server и обслуживающих его адаптеров гораздо выше.

**Comment by buybackoff** [comment]
Вот она, сила Lua! :) Люблю этот язык, как познакомился Redis! Разработчики Квика молодцы в этом! Если вдруг захотите что-то добавить в QuikSharp, буду только рад!

**Comment by qkgx** [comment]
И это заметно! :) На мой взгляд Ваша библиотека очень профессионально сделана, причем и с точки зрения предметной области (обработка торговых событий, аккумулирование сделок по заявке), и с точки зрения программирования (организация кода, межпроцессное взаимодействие и т.п.).

Я пока вот разбираюсь в чем же причины такого странного поведения (что в одном боксе Quik зависает а в другом нет). Для production торговых систем очень важно понимать все входы и выходы.

Для Вашей статистики: за сегодня программа (Windows Forms Application) получила 1.5 млн стаканов по Срочному рынку и 1.2 млн сделок. Без перезагрузок, перезапусков и без торможения Quik.

**Comment by buybackoff** [comment]
Спасибо за фидбек!

**Comment by buybackoff** [comment]
Хорошо бы проверить другую версию Квика на той же машине, где зависает. Если снова будет зависать, то дело в Квике, иначе дело в коде/версии .NET/Windows.

**Comment by qkgx** [comment]
Похоже, помогла перезагрузка машины (я ее первый раз в этом году перезагружал)

**Comment by vfreeeman** [comment]
а для ваших задач случаем не было необходимости получение следующей информации:
информация по инструменту
список доступных инструментов

как пользоваться функциями GetSecurityInfo и GetClassSecurities я не понял.
пробовал так - не получилось
var _quik = new Quik();
var si=_quik.Class.GetSecurityInfo("QJSIM", "LKOH");
si.Wait(); // var res=si.Result;

**Comment by qkgx** [comment]
@vfreeeman, статику по инструментам я получаю получаю через ODBC

**Comment by buybackoff** [comment]
@vfreeeman все тесты работают, ошибка у вас. нет такого класса QJSIM, LKOH числится в классе TQBR

GetSecurityInfo for LKOH: {"sec_code":"LKOH","name":"НК ЛУКОЙЛ (ОАО) - ао","short_name":"ЛУКОЙЛ","class_code":"TQBR","class_name":"МБ ФР: Т+ Акции и ДР","face_value":"0","face_unit":"SUR","scale":1,"mat_date":"20150430","lot_size":1}

**Comment by vfreeeman** [comment]
QJSIM - это класс в QUIK-Junior - я пока там смотрю

**Comment by buybackoff** [comment]
Тесты показывают, как взять все классы и все инструменты по классам, должно все работать с правильными кодами

**Comment by qkgx** [comment]
Про 1000 стаканов я погорячился: "Превышено ограничение на количество котировочных окон. Одновременно может быть открыто не более 200 окон"

Видимо при подписке на стакан через API это ограничение тоже действует.

**Comment by qkgx** [comment]
@buybackoff, а можно ли в едином адресном пространстве использовать несколько экземляров QuikSharp.Quik соединяющихся с разными терминалами Quik по разным портам - они не будут конфликтовать друг с другом?

Я хотел бы сделать прозрачное получение данных с нескольких квиков. Т.е. платформа запрашивает стакан, далее балансировщик подписывается к одному из квиков (платформа не знает к какому) и унифицированным образом предоставляет ей данные.

Это на случай если 200 стаканов не хватит.

**Comment by buybackoff** [comment]
нужно будет менять порт в Луа и создавать отдельные instances of QuikSharp.Quik(port). делать транспарентный балансировщик наверное можно (но я не буду). можно подписать один и тот же call back на собития разных instances of QuikSharp.Quik(port), а подписки делить по первой букве или еще как-нибудь.

**Comment by RomanS2N** [comment]
Не забудьте ещё авторизацию при подключении к lua поставить, а то будут ламать как орехи

**Comment by buybackoff** [comment]
@RomanS2N в планах еще AES, RSA и PGP шифрование (одновременно), чтобы АНБ и ФСБ не палило сделки :)

**Comment by RomanS2N** [comment]
Биржа сама спалит если нужно :)

**Comment by qkgx** [comment]
@RomanS2N, пока как вариант можете организовать связку "программа - lua" поверх VPN туннеля. И безопасно, и не потребуется ничего переписывать.

**Comment by RomanS2N** [comment]
Авторизацию я бы поставил, что бы сканеров обходить, а так в lua какой нидудь ключ всё таки добавить непомешало бы, при каждой новой сессии делать сравнеие с ним (типа чужой-свой), чем через vpn тунель все гнать,тем более у VPN точка входа и выхода не чем не шифруются, а здесь речь идёт именно о защите подключения к Квику. 
Посмотрим что Виктор выпустит в окончательной концепции, если всё таки будет заниматься проектом ;)

**Comment by buybackoff** [comment]
Вы не поняли сарказма про шифрование!? Может к 2050 году что-нибудь выпущу,
это настолько за пределами проекта, что я даже пулл реквесты на эту тему не
хочу. Безопасность - проблема решенная и не моя. Какие сканеры!? Вы о чем!?
Крутите у себя на машине или на VPN AWS за firewall-ом.

Единственное, что мне могло бы быть интересно - заменить TCP на TLS/SSL,
быстрый поиск дает пример:
http://lua-users.org/lists/lua-l/2009-02/msg00270.html. Но раньше 2050 года
я сам вряд ли этим займусь.


2015-05-04 22:03 GMT+03:00 RomanS2N <notifications@github.com>:
