### ISSUE TITLE
квик

### ISSUE THREAD

**Issue by RomanS2N** [buybackoff/QuikSharp#16]
Скоро опять архитектуру менять нужно http://quik.ru/news/?id=2298, на MICEX Bridge обратите внимание.

**Comment by buybackoff** [comment]
криптографическая новость, ничего не понятно. архитектуру этого проекта менять будет не нужно, если Луа останется, вопрос лишь API signatures.

**Comment by RomanS2N** [comment]
Я к тому что без Луа можно обойтись.
