### ISSUE TITLE
Расширенная информация по инструментам && производительность

### ISSUE THREAD

**Issue by dvoris** [buybackoff/QuikSharp#20]
а) возможно ли получать расширенную информацию по инструментам (аналог столбцов из таблицы текущих значений - волатильность для опционов и прочее)? Видимо, на стороне LUA это функция getParamEx.
б) не будет ли проблемно получать обновления инструментов, если их будет две-три сотни (опционы)? В одном из сторонних аналогичных решений встретил такой коммент 
"-- ВАЖНО!!! Если Вы добавите в фильтр функции OnParam() много бумаг для передачи,
-- задержка сильно увеличится. Для примера: если отправлять все бумаги 
-- классов TQBR (акции), SPBFUT (фьючерсы) и SPBOPT (опционы),
-- то время задержки может достигать 10 секунд и более, в зависимости от интенсивности торгов."
Такая задержка, конечно, была бы неприемлема.

**Comment by buybackoff** [comment]
Если что-то есть в Луа, все можно получать из QuikSharp по аналогии с реализованными функциями. Ограничения по скорости/количеству могут быть связаны только с Квиком, или со скоростью интернет соединения.
