### ISSUE TITLE
Непонятки с Newtonsoft.Json и Esent.xxxx

### ISSUE THREAD

**Issue by Pr0phet1c** [buybackoff/QuikSharp#23]
Скачал проект QuikSharp-master, запустил в VS.
После разных манипуляций Newtonsoft.Json и Esent.xxxx в проекте "Profiler" видятся нормально (проект можно скомпилировать и запустить).
А вот дальше не знаю что делать.

В проекте "QiukSharp.Tests" в References -- > Newtonsoft.Json с восклицательным знаком и ошибки следующего вида:
Ошибка	1	Не удалось найти имя типа или пространства имен "Newtonsoft" (пропущена директива using или ссылка на сборку?)	C:\Users\Владислав\Dropbox\C#\Чужое\QuikSharp-master\tests\QuikSharp.Tests\TransactionSpecTest.cs	4	7	QuikSharp.Tests

В проекте "QiukSharp" - те же проблемы, но плюс еще и с Esent.xxxx

Знания в C# на начальном уровне. Просьба сильно не пинать, если вопрос получился идиотский.
Рискну предположить, что автору проекта без моих "нубских" вопросов забот хватает, но может кто-то уже решал такую проблему?

P.S.: Проект реально очень актуальный (более десятка одновременно работающих ботов на QLua в одном терминале уже начинают порождать различные неудобства), хочется всю логику вынести за пределы терминала.

**Comment by buybackoff** [comment]
Это не имеет отношение к КвикШарпу, это вопрос работы с проектами в Visual Studio, сорри. У меня и людей строится и запускается без дополнительных танцев с бубнами. Замый простой пример использования - скомпилировать сам QuikSharp как console application, там файл Program.cs.

**Comment by Pr0phet1c** [comment]
В том-то и проблема, что проект невозможно скомпилировать, т.к. при анализе
кода вылезают ошибки.
Я просто не могу понять как в одной сборке, содержащей 3 проекта, в одном
проекте подключенные модули видятся, а в других двух нет.
Извините, что отнял у Вас время.

2015-09-24 11:11 GMT+03:00 Victor Baybekov <notifications@github.com>:

**Comment by buybackoff** [comment]
Обновите все пакеты NuGet вручную до последних, проверьте глазами, что все
references рабочие, без желтых восклицательных иконок. Даже последняя
Visual Studio жестко тупит порой с ссылками и пакетами НюГет.

2015-09-24 13:57 GMT+03:00 Pr0phet1c <notifications@github.com>:

**Comment by SkyN** [comment]
отпишусь, может кому-нибудь сэкономлю день.

скомпилировать проект мне помогла команда, набранная в Package Manager Console:
**Update-Package -Reinstall**
делает она следующее: Reinstall all packages in ALL PROJECTS of the current solution
