### ISSUE TITLE
Как подписываться на свечки?

### ISSUE THREAD

**Issue by SkyN** [buybackoff/QuikSharp#28]
Из NuGet скачал QuikSharp.0.2.0 и попытался повторить пример из CandlesSubscriptionTest.
В классе Quik нет определения для Candles, в итоге не смог найти функцию Subscribe. 

Подумал что разработка на github  ушла вперед, и попытался собрать версию из github в Visual Studio 2015, но собираться не захотела, зависимости оказались битыми, застрял на Microsoft.Isam.

Так как же подписаться на Events.OnAllTrade ?

**Comment by buybackoff** [comment]
НюГет давно не обновлялся. Проект собирается нормально у большинства, установите все НюГет зависимости. Все примеры, что есть, в тестах и Program.cs. Других нет и пока не будет.

**Comment by SkyN** [comment]
отпишусь, может кому-нибудь сэкономлю день.

скомпилировать проект мне помогла команда, набранная в Package Manager Console:
**Update-Package -Reinstall**
делает она следующее: Reinstall all packages in ALL PROJECTS of the current solution
