### ISSUE TITLE
Candles

### ISSUE THREAD

**Issue by RomanS2N** [buybackoff/QuikSharp#4]
Уточните, а как при помощи вашей библиотеки получить свечи? В примерах не нашёл, есть вообще такая возможность?

**Comment by buybackoff** [comment]
Добавить функцию по аналогии с предыдущими и прислать pull request :)

**Comment by RomanS2N** [comment]
"Добавить функцию по аналогии с предыдущими" - не совсем понял, по аналогии с какими предыдущими

**Comment by buybackoff** [comment]
Реализованными callbacks - например по ордеру. У меня реализован каждый тип функций, а конкретно сами функции я не пытался все реализовать в надежде, что кто-то присоединится и поможет допилить функционал. У меня пока нет времени допилиливать и полировать эту тему. Возможно где-то через месяц вернусь к коду.

Стокшарп *как бы* стал open source, хотя бы на каплю больше, чем был, интересно почему Вы им не пользуетесь? https://github.com/stocksharp/stocksharp

**Comment by buybackoff** [comment]
[Здесь](https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/lua/qsfunctions.lua) или [здесь](https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/lua/qscallbacks.lua) надо добавить функцию согласно документации QLua, отсальной функционал Луа их без проблем распознает.  Затем руками или лучше с помощью Эксель файла нужно создать структуру данных/POCO class в C#, которая 1-в-1 соотвествует таблице из документации QLua ([example](https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/DataStructures/AllTrade.cs)). После этого сделать C# версию этих функций по аналогии с https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/OrderBookFunctions/OrderBookFunctions.cs. В основном это работа по копирова-вставить и не сделать опечаток.

**Comment by RomanS2N** [comment]
А qapi_.lua разве не со свечками работает? 
Стокшарп запутан и багов больше чем надо, да и честно не все там открыто, та же дравина Lua которую в Квик заливают в dll мешке передаётся, а не исходником. Но у каждого проекта свой гемморой, поэтому я сейчас смотрю все подходы stocksharp и ваш в том числе. :)

**Comment by buybackoff** [comment]
Qapi_.lua это вообще отдельный проект с просторов сети, у меня лежит просто
так для примера, может там что-то полезное найдется положить на сторону Луа
и вызывать из С#.

**Comment by RomanS2N** [comment]
Да со свечками там нужно поработать, именно этот вывод что спользует Qapi_.lua, много времени сьедает. :(
Кстати, я смотрю в том же StockSharp сразу подключается внешняя библиотека в которой определенны LUA функции, а у через скрипты данные отправляются, может в этом и проблема с 60 мс? :)

**Comment by buybackoff** [comment]
60 микро, а не милли - это вообще не проблема. Я сомневаюсь, что можно добиться "более лучшего" результата, на стороне Луа все бибилотеки на C (tcp,json), localhost loop обходит сетевую карту и по сути обмен данными через память.

**Comment by RomanS2N** [comment]
Ну не совсем tcp,ip - это сетевой протакол по которуму текстовой код json гоняют, ну бог с ним.
А что здесь: QuikSharp/src/QuikSharp/lua/clibs/ ?

Конечно, решение у вас ещё очень сырое (это может и даже плюс, можно более гибкий и простой вариант сделать). 
Кроме свечей и индикатором в едином формате, логирование и диагностику добавить бы, заявки в простом виде, да и торговый инструментарий расширить.
Хотя можно на будушее сделать единую систему обработки, а конекторы просто меня если планируется работать с несколькими системами.

Так конечно над чертёхной доской бы нужно поседеть вам и начертить оптимальную структуру проекта перед тем как работать над ним, а то кусками начнете делать - прийдётся подгонять постоянно.

Ну это к слову, мое мнения как инженера сетевых проектов :)

**Comment by buybackoff** [comment]
Пожалуйста, pull requests открыты для всех! Посидите над доской, подумайте, сделайте логирование, GUI, order management, risk management,единую систему обработки... Еще один клон StockSharp нам очень нужен!

**Comment by RomanS2N** [comment]
Клон StockSharp, а что вы сами хотите что бы с вашего проекта получилось?

**Comment by buybackoff** [comment]
Я ничего не хочу. Я выложил вдруг кому пригодится. Структура сделана с учетом расширения на всю API, нужно что-то - как дописать я рассказал.

**Comment by RomanS2N** [comment]
Если его не развивать к какой-то логической точки, он и останится как структура для других проектов.
Что всё таки в кармушки: QuikSharp/src/QuikSharp/lua/clibs/ ?

**Comment by buybackoff** [comment]
Я сделал лицензию Apache - теперь можно разбирать на куски, брать себе, главное не забыть ссылку. А не полнял вопрос - в папке dll библиотеки для Луа: tcp, json и прокси lua51.dll для lua5.1.dll (Квик забыли/не стали добавлять эту прокси без точки)

**Comment by RomanS2N** [comment]
Все по дровам понял.

**Comment by RomanS2N** [comment]
Надеюсь, хоть у вас поидёт какое-то далнейшее развитие, т.к. существующие проекты очень далеки от нужд трейдинга и честно сказать неудачны. О том же LEAN: 
https://www.quantconnect.com/forum/discussions - поэтому и не особо они популярны.

**Comment by buybackoff** [comment]
Я развиваю пока в зыкрытом режиме проект в несколько другой области и нет
цели сделать что-то большое в нише Lean/StockSharp. Объекная модель Lean
меня после беглого взгляда не достаточна для моих нужд, но там модульная
архитектура и я думаю взять ее за основу. Но пока глубоко еще не смотрел в
их код.

2015-04-03 18:35 GMT+03:00 RomanS2N <notifications@github.com>:

**Comment by RomanS2N** [comment]
Модульность это хорошо!
Кстати, XlDde ещё добавте в свою библиотеку.

**Comment by buybackoff** [comment]
На все "добавьте", "сделайте" я вежливо посылаю на pull requests.

**Comment by buybackoff** [comment]
#15 закрывает это
